"""Initial migration.

Revision ID: 1dcb1a5c10d4
Revises: 
Create Date: 2024-08-31 10:30:23.223887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcb1a5c10d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('author', sa.String(length=60), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('benefit_created_on',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('benefit_updated_on',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('benefit_updated_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('benefit_created_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    op.drop_table('post')
    # ### end Alembic commands ###
