"""modified db schema

Revision ID: 5823aefae629
Revises: e34736620700
Create Date: 2024-09-02 16:54:54.534343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5823aefae629'
down_revision = 'e34736620700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=False)
        batch_op.alter_column('benefit_image',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('benefit_requirement',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('benefit_link',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('benefit_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefit_duration', sa.INTEGER(), nullable=False))
        batch_op.alter_column('benefit_link',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('benefit_requirement',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
        batch_op.alter_column('benefit_image',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=60),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
