"""added date_posted to Post class

Revision ID: b40523d54e78
Revises: 5823aefae629
Create Date: 2024-09-04 22:48:25.295894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40523d54e78'
down_revision = '5823aefae629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('benefit_created_on',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('benefit_updated_on',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_column('benefit_description')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefit_description', sa.VARCHAR(length=160), nullable=True))
        batch_op.alter_column('benefit_updated_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('benefit_created_on',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###
