"""remove unique constraint on benefit_requirement

Revision ID: d5535d4c6816
Revises: 25c667f93b3b
Create Date: 2024-08-31 21:02:58.114043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5535d4c6816'
down_revision = '25c667f93b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('benefit_requirement',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.alter_column('benefit_requirement',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
