"""add back columns image and requirement

Revision ID: e34736620700
Revises: ee42ed01946e
Create Date: 2024-08-31 21:26:35.812559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34736620700'
down_revision = 'ee42ed01946e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefit_image', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('benefit_requirement', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.drop_column('benefit_requirement')
        batch_op.drop_column('benefit_image')

    # ### end Alembic commands ###
