"""remove problematic columns

Revision ID: ee42ed01946e
Revises: d5535d4c6816
Create Date: 2024-08-31 21:06:12.199663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee42ed01946e'
down_revision = 'd5535d4c6816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.drop_column('benefit_image')
        batch_op.drop_column('benefit_requirement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benefit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefit_requirement', sa.VARCHAR(length=160), nullable=True))
        batch_op.add_column(sa.Column('benefit_image', sa.VARCHAR(length=60), nullable=True))

    # ### end Alembic commands ###
